version: "3"

services:

  solr:
#    image: wodby/drupal-solr:7-5.4
    image: demonz/appservice-drupal-solr:7.x-5.5
    environment:
      SOLR_HEAP: 1024m
      SOLR_USER: drupal
      SOLR_PASSWORD: solrpass
      WEBSITES_REQUIRE_IP: "Require ip 172.25.0.3 172.25.0.4 172.25.0.5 172.25.0.6 172.25.0.7"
      WEBSITES_HOST: solr
      WEBSITES_PORT: 80
    volumes:
      - ./data:/home
    ports:
      - "8983:8983"
      - "2222:2222"

# is there a way to initialise the default core on first run?
# docker-compose exec solr /usr/local/bin/init_solr localhost
