version: "3"

services:

  solr:
#    image: wodby/drupal-solr:7-5.4
    image: nbcwebcontainers.azurecr.io/appservice-drupal-solr:7.x-5.5
    environment:
      SOLR_HEAP: 1024m
      SOLR_USER: drupal
      SOLR_PASSWORD: solrpass
      WEBSITES_PORT: 80
      WEBSITES_HOST: solr
    volumes:
      - ./data:/home
    ports:
      - "8983:8983"
      - "2222:2222"

# is there a way to initialise the default core on first run?
# docker-compose exec solr /usr/local/bin/init_solr localhost
