version: "3"

services:

  solr:
#    image: wodby/drupal-solr:7-5.4
    image: demonz/appservice-drupal-solr:7.x-5.5
    environment:
      SOLR_HEAP: 1024m
      SOLR_USER: drupal
      SOLR_PASSWORD: solrpass
      APACHE_REQUIREIP: "172"
      WEBSITES_HOST: solr
      WEBSITES_PORT: 80
    volumes:
      - ./data:/home
    ports:
      - "8983:8983"
      - "2222:2222"
